// This file is normally generated by the FlutterFire CLI.
//
// IMPORTANT:
// - For Firebase to work on Flutter Web, Firebase.initializeApp MUST be given
//   FirebaseOptions.
// - Run: flutterfire configure
//   (or: dart pub global run flutterfire_cli:flutterfire configure)
// - The generated file will overwrite these placeholder values.
//
// Until you configure Firebase, the app will show a setup message.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return web;
    }
  }

  // Placeholder options: replace by running FlutterFire CLI.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABmMYKT8DY4JzIh27IrEbeHy5wjNsdYYE',
    appId: '1:46273244188:web:0549e18e943df4eeaec3d9',
    messagingSenderId: '46273244188',
    projectId: 'smart-class-checkin-7b215',
    authDomain: 'smart-class-checkin-7b215.firebaseapp.com',
    storageBucket: 'smart-class-checkin-7b215.firebasestorage.app',
    measurementId: 'G-Q637M7GBPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    iosBundleId: 'REPLACE_ME',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    iosBundleId: 'REPLACE_ME',
  );

  // Desktop targets are not used for this lab MVP.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
  );
}
